<div id="main" class="l-border r-border span-15">

    <h1 id="Title"><a href="#Title">Archive</a></h1>

    <p>
        Compress and Extract archive on common format without any binary or
        PEAR Extention.
    </p>

    <h2 id="Syntax"><a href="#Syntax">Syntax</a></h2>
    <p>
        @todo
    </p>

    <h2 id="Functions"><a href="#Functions">Functions</a></h2>
    <p>
        @todo
    </p>

</div>


<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#Title">Archive</a></h4>
    <div class="menu-item"><a href="#Syntax">Syntax</a></div>
    <div class="menu-item"><a href="#Functions">Functions</a></div>
</div>

