<div id="main" class="l-border r-border span-15">

    <h1 id="Title"><a href="#Title">Controller Abstract</a></h1>
    <p>
        Bla bla...
    </p>

    <h1 id="Functions"><a href="#Functions">Functions</a></h1>
    <p>
        Bla bla...
    </p>

</div>

<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#Title">Controller Abstract</a></h4>
    <h4 class="menu-item"><a href="#Functions">Functions</a></h4>
    <div class="menu-item"><a href="#initModule">initModule</a></div>
    <div class="menu-item"><a href="#initController">initController</a></div>
    <div class="menu-item"><a href="#setLayout">_setLayout</a></div>
    <div class="menu-item"><a href="#makeHtml">_makeHtml</a></div>
    <div class="menu-item"><a href="#makeAjax">_makeAjax</a></div>
    <div class="menu-item"><a href="#makeAjaxHtml">_makeAjaxHtml</a></div>
    <div class="menu-item"><a href="#addAjax">_addAjax</a></div>
    <div class="menu-item"><a href="#makeJson">_makeJson</a></div>
    <div class="menu-item"><a href="#addJson">_addJson</a></div>
    <div class="menu-item"><a href="#setJson">_setJson</a></div>
</div>
