<div id="main" class="l-border r-border span-15">

    <h2 id="Tabs"><a href="#Section">Classic Select</a></h2>

    <h3>Syntax:</h3>

    <?php
        $source= array();
        $source[] = "\$examples = new MyProject_Collection_Db('example', array(3, 4));";
		$source[] = "foreach (\$examples as \$example) {";
            $source[] = "echo \$example->getId() . '/' . \$example->creation . '<br />';";
        $source[] = "}";

        echo $this->GeSHi(implode("\n", $source), 'php');
    ?>


    <h3>Example:</h3>

	<?php 
		/*
		$examples = new MyProject_Collection_Db('example', array(3, 4));
        foreach ($examples as $example) {
            echo $example->getId() . '/' . $example->creation . "<br />";
        }
        */
	?>

    <br />
    <br />
    
    <h2 id="Tabs"><a href="#Section">Complex Select</a></h2>

    <h3>Syntax:</h3>

    <?php
        $source= array();
        
        $source[] = "\$examples = new MyProject_Collection_Db('example');";
		$source[] = "\$examples->filterJoin('example_type', 'example.example_type_id = example_type.example_type_id')";
		$source[] = "\$examples->filterWhere('example.example_id > ?', 1)";
		$source[] = "\$examples->filterWhere('(example.example_type_id = 1 OR example.example_type_id = 2)')";
		$source[] = "\$examples->filterOrderBy('example_id DESC')";
		$source[] = "\$examples->filterLimit(10)";
		$source[] = "\$examples->filterExecute();";
		
		$source[] = "foreach (\$examples as \$example) {";
            $source[] = "echo \$example->getId() . '/' . \$example->example_type_id . '<br />';";
        $source[] = "}";

        echo $this->GeSHi(implode("\n", $source), 'php');
    ?>


    <h3>Example:</h3>

	<?php 
		/*
        $examples = new MyProject_Collection_Db('example');
        $examples->filterJoin('example_type', 'example.example_type_id = example_type.example_type_id')
        		->filterWhere('example.example_id > ?', 1)
        		->filterWhere('(example.example_type_id = 1 OR example.example_type_id = 2)')
        		->filterOrderBy('example.example_id DESC')
        		->filterLimit(10)
        		->filterExecute();
        		
        foreach ($examples as $example) {
            echo $example->getId() . '/' . $example->example_type_id . "<br />";
        }
        */
	?>

    <br />
    <br />
    
    <h2 id="Tabs"><a href="#Section">Relation</a></h2>

    <h3>Syntax:</h3>

    <?php
        $source= array();
        
        $source[] = "\$examples = new MyProject_Collection_Db('example');";
		$source[] = "\$examples->filterJoin('example_type', 'example.example_type_id = example_type.example_type_id')";
		$source[] = "\$examples->filterWhere('example.example_id > ?', 1)";
		$source[] = "\$examples->filterWhere('(example.example_type_id = 1 OR example.example_type_id = 2)')";
		$source[] = "\$examples->filterOrderBy('example_id DESC')";
		$source[] = "\$examples->filterLimit(10)";
		$source[] = "\$examples->filterExecute();";
		
		$source[] = "foreach (\$examples as \$example) {";
            $source[] = "echo \$example->getId() . '/' . \$example->Example_type->label . '<br />';";
        $source[] = "}";

        echo $this->GeSHi(implode("\n", $source), 'php');
    ?>


    <h3>Example:</h3>

	<?php 
        $examples = new MyProject_Collection_Db('example');
        $examples->filterJoin('example_type', 'example.example_type_id = example_type.example_type_id')
        		->filterWhere('example.example_id > ?', 1)
        		->filterWhere('(example.example_type_id = 1 OR example.example_type_id = 2)')
        		->filterOrderBy('example.example_id DESC')
        		->filterLimit(10)
        		->filterExecute();
        		
        foreach ($examples as $example) {
            echo $example->getId() . '/' . $example->Example_type->label . "<br />";
        }
	?>
</div>
