<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">Error Handler</a></h1>
    <p>
        @todo
    </p>

    <h2 id="Example"><a href="#Example">Example</a></h2>
    <p>
        This an example of error handlings for an undefined variable.
    </p>

    <iframe height="600" src="/example/core/error?error=1&<?php echo DEBUG_REMOTE_TOKEN; ?>=1"></iframe>

    <h2 id="Remote"><a href="#Remote">Remote Debug</a></h2>
    <p>
        @todo
    </p>

    <h2 id="Report"><a href="#Report">Error Report</a></h2>
    <p>
        @todo
    </p>

</div>

<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#Title">Error Handler</a></h4>
    <div class="menu-item"><a href="#Example">Example</a></div>
    <div class="menu-item"><a href="#Remote">Remote Debug</a></div>
    <div class="menu-item"><a href="#Report">Error Report</a></div>
</div>
