<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">Notify</a></h1>

    <p>
        Used to displaying a message and destuct it after it displayed, just a little notify system.
    </p>

    <h2 id="Usage"><a href="#Usage">Usage</a></h2>

    <h2 id="Functions"><a href="#Functions">Functions</a></h2>
    <h3 id=""><a href="#getInstance">Function: getInstance</a></h3>
    <h3 id=""><a href="#set">Function: set</a></h3>
    <h3 id=""><a href="#get">Function: get</a></h3>
    <h3 id=""><a href="#getAll">Function: getAll</a></h3>
    <h3 id=""><a href="#delete">Function: delete</a></h3>
    <h3 id=""><a href="#isExist">Function: isExist</a></h3>

</div>

<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#Title">Notify</a></h4>
    <div class="menu-item"><a href="#getInstance">getInstance</a></div>
    <div class="menu-item"><a href="#set">set</a></div>
    <div class="menu-item"><a href="#get">get</a></div>
    <div class="menu-item"><a href="#getAll">getAll</a></div>
    <div class="menu-item"><a href="#delete">delete</a></div>
    <div class="menu-item"><a href="#isExist">isExist</a></div>
</div>
