<div id="main" class="l-border r-border span-15">

    <h1 id="intro"><a href="#intro">StItem</a></h1>

    <p class="description">
        Bla bla...
    </p>

    <h2 id=""><a href="#">Function: getId</a></h2>
    <h2 id=""><a href="#">Function: getExtendedId</a></h2>
    <h2 id=""><a href="#">Function: getIdFromExtendedId</a></h2>
    <h2 id=""><a href="#">Function: getStItemExtendedId</a></h2>
    <h2 id=""><a href="#">Function: getProperty</a></h2>
    <h2 id=""><a href="#">Function: getProperties</a></h2>

    <h1 id="intro"><a href="#intro">StCollection</a></h1>

    <h2 id=""><a href="#">Function: getInstance</a></h2>
    <h2 id=""><a href="#">Function: getProperty</a></h2>
    <h2 id=""><a href="#">Function: getProperties</a></h2>

</div>


<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#intro">StItem</a></h4>

    <div class="menu-item"><a href="#">getId</a></div>
    <div class="menu-item"><a href="#">getExtendedId</a></div>
    <div class="menu-item"><a href="#">getIdFromExtendedId</a></div>
    <div class="menu-item"><a href="#">getStItemExtendedId</a></div>
    <div class="menu-item"><a href="#">getProperty</a></div>
    <div class="menu-item"><a href="#">getProperties</a></div>


    <h4 class="menu-item"><a href="#intro">StCollection</a></h4>

    <div class="menu-item"><a href="#">getInstance</a></div>
    <div class="menu-item"><a href="#">getProperty</a></div>
    <div class="menu-item"><a href="#">getProperties</a></div>
</div>

