<div id="main" class="l-border r-border span-15">

    <h1 id="Title"><a href="#Title">Template</a></h1>

    <p>
        Provide to your customers, marketing team or webdesigner a simple way to make their
        models/template for mail or displayed messages by using a simple and fast template language.
    </p>


    <ul>
        <li>Implement token like IF/BEGIN/CONST</li>
        <li>Simple string, PHP array, ArrayObject Class and Iterator Class has template variables</li>
        <li>Simple class usage</li>
        <li>Possibilty to bind variables with model layer</li>
    </ul>


    <h2 id="Example"><a href="#Example">Example usage</a></h2>
    <?php

        $source = array();
        $source[] = '// declare template variables';
        $source[] = '$data = array(';
        $source[] = "    'titi' => rand(1, 3),";
        $source[] = "    'tata' => array(";
        $source[] = "        'tutu' => time(),";
        $source[] = "        'tete' => time(),";
        $source[] = '    ),';
        $source[] = "    'data' => array(";
        $source[] = "        array('unique_string' => 'titi'),";
        $source[] = "        array('unique_string' => 'toto'),";
        $source[] = '    ),';
        $source[] = ');';
        $source[] = '';
        $source[] = '// declare template source';
        $source[] = '$tplString = "<pre>                                                                   ';
        $source[] = 'test string with var name   : titi                                      ';
        $source[] = 'test var                    : titi={titi}                               ';
        $source[] = 'test if titi == 1           : [if: {titi} == 1 ? titi=true : titi=false]';
        $source[] = 'test var array assoc        : {tata:tutu}                               ';
        $source[] = 'test const                  : [const:BASE_PATH]                         ';
        $source[] = '                                                                        ';
        $source[] = '[begin:{datas}]                                                         ';
        $source[] = 'test begin/end with limit   : {data:unique_string}                      ';
        $source[] = '[end:{datas}]                                                           ';
        $source[] = '</pre>";                                                                ';
        $source[] = '';
        $source[] = '// create a new template';
        $source[] = '$tpl = new BaseZF_Template();';
        $source[] = '';
        $source[] = '// set template source';
        $source[] = '$tpl->setTemplate($tplString);';
        $source[] = '';
        $source[] = '// set binded variables';
        $source[] = '$tpl->setData($data);';
        $source[] = '';
        $source[] = '// then render it';
        $source[] = '$tplRendered = $tpl->render();';

        echo $this->GeSHi(implode("\n", $source), 'php');
    ?>

    <h1 id="Functions"><a href="#Functions">Functions</a></h1>

    <h2 id="setTemplate"><a href="#setTemplate">setTemplate</a></h2>
    <h2 id="setData"><a href="#setData">setData</a></h2>
    <h2 id="render"><a href="#render">render</a></h2>
    <p>
        @todo
    </p>

</div>


<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#Title">Archive</a></h4>
    <div class="menu-item"><a href="#Example">Example usage</a></div>
    <h4 class="menu-item"><a href="#Functions">Functions</a></h4>
    <div class="menu-item"><a href="#setTemplate">setTemplate</a></div>
    <div class="menu-item"><a href="#setData">setData</a></div>
    <div class="menu-item"><a href="#render">render</a></div>
</div>

