<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">Debug</a></h1>

    <p>
        @todo
    </p>

    <h2 id="Section"><a href="#Section">Section</a></h2>

    <p>
        @todo
    </p>

    <h3 id="">Sub Sections</h3>

    <p>
        @todo
    </p>

</div>

<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#Title">Debug</a></h4>
    <div class="menu-item"><a href="#Section">Section</a></div>
</div>
