<div id="main" class="l-border r-border span-15">

    <h1 id="intro"><a href="#title">Makefile</a></h1>

    <p class="description">
        You can use the Makefile scripts at the root of projects with following arguments
        to make fast and simple automatised tasks.
    </p>

    <h2 id="usage"><a href="#usage">Usage</a></h2>
    <p class="description">

    <?php

        $source = array(
            '# cd /myproject/',
            '# make <callbacks>',
        );

        echo $this->GeSHi(implode("\n", $source), 'bash');
    ?>

    </p>

    <h1 id="callbacks"><a href="#callbacks">Callbacks</a></h1>

    <h2 id="syntax"><a href="#doc">doc</a></h2>
    <p class="description">
        Generate the doxygen doc on &lt;myproject_path&gt;/doc/ directory from config file available in &lt;myproject_path&gt;/etc/doxygen.conf You can see this documentation online at /debug/doc.
    </p>

    <h2 id="syntax"><a href="#syntax">syntax</a></h2>
    <p class="description">
        Run implemented syntax checking, currently it is an alias of php-syntax callback.
    </p>

    <h2 id="test"><a href="#test">test</a></h2>
    <p class="description">
        Run implemented UnitTest, currently it is an alias of php-phpunit callback
    </p>

    <h2 id="config"><a href="#config">config</a></h2>
    <p class="description">
        Run &lt;myproject_path&gt;/tools/config-generator.php to deploy config template files available in &lt;myproject_path&gt;/etc/dist/ in &lt;myproject_path&gt;/etc/.
    </p>

    <h2 id="config"><a href="#php-qa">php-qa</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="config"><a href="#config">php-phpcpd</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="config"><a href="#config">php-phpcs</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="config"><a href="#config">php-phploc</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="config"><a href="#config">php-phpunit</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="config"><a href="#config">php-syntax</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="config"><a href="#config">php-syntax-commit</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="locale"><a href="#locale">locale</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="locale-template"><a href="#locale-template">locale-template</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="locale-update"><a href="#locale-update">locale-update</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="locale-deploy"><a href="#locale-deploy">locale-deploy</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="locale-deploy-fuzzy"><a href="#locale-deploy-fuzzy">locale-deploy-fuzzy</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="locale-translate-google"><a href="#locale-translate-google">locale-translate-google</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="locale-clean"><a href="#locale-clean">locale-clean</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="static-pack"><a href="#static-pack">static-pack</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="static-pack-css"><a href="#static-pack-css">static-pack-css</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="static-pack-js"><a href="#static-pack-js">static-pack-js</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="log-clean"><a href="#log-clean">log-clean</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="log-archive"><a href="#log-archive">log-archive</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="clean"><a href="#clean">clean</a></h2>
    <p class="description">
        @todo
    </p>

</div>


<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#title">Makefile</a></h4>
    <div class="menu-item"><a href="#usage">Usage</a></div>

    <h4 class="menu-item"><a href="#callbacks">Callbacks</a></h4>
    <div class="menu-item"><a href="#doc">doc</a></div>
    <div class="menu-item"><a href="#syntax">syntax</a></div>
    <div class="menu-item"><a href="#test">test</a></div>
    <div class="menu-item"><a href="#config">config</a></div>
    <div class="menu-item"><a href="#php-qa">php-qa</a></div>
    <div class="menu-item"><a href="#php-phpcpd">php-phpcpd</a></div>
    <div class="menu-item"><a href="#php-phpcs">php-phpcs</a></div>
    <div class="menu-item"><a href="#php-phploc">php-phploc</a></div>
    <div class="menu-item"><a href="#php-phpunit">php-phpunit</a></div>
    <div class="menu-item"><a href="#php-syntax">php-syntax</a></div>
    <div class="menu-item"><a href="#php-syntax-commit">php-syntax-commit</a></div>
    <div class="menu-item"><a href="#locale">locale</a></div>
    <div class="menu-item"><a href="#locale-template">locale-template</a></div>
    <div class="menu-item"><a href="#locale-update">locale-update</a></div>
    <div class="menu-item"><a href="#locale-deploy">locale-deploy</a></div>
    <div class="menu-item"><a href="#locale-deploy-fuzzy">locale-deploy-fuzzy</a></div>
    <div class="menu-item"><a href="#locale-translate-google">locale-translate-google</a></div>
    <div class="menu-item"><a href="#locale-clean">locale-clean</a></div>
    <div class="menu-item"><a href="#static-pack">static-pack</a></div>
    <div class="menu-item"><a href="#static-pack-css">static-pack-css</a></div>
    <div class="menu-item"><a href="#static-pack-js">static-pack-js</a></div>
    <div class="menu-item"><a href="#log-clean">log-clean</a></div>
    <div class="menu-item"><a href="#log-archive">log-archive</a></div>
    <div class="menu-item"><a href="#clean">clean</a></div>
</div>

