<?php
/**
 * Default layout for MyProject
 *
 * @category   MyProject
 * @package    MyProject_App_Layouts
 * @copyright  Copyright (c) 2008 MyProject
 * @author     Harold Thetiot (hthetiot)
 */

    // add blueprint stylesheet
    $this->headLink()->appendStylesheet('/css/lib/blueprint/blueprint/screen.css', 'screen, projection');
    $this->headLink()->appendStylesheet('/css/lib/blueprint/blueprint/print.css', 'print');
    $this->headLink()->appendStylesheet('/css/lib/blueprint/blueprint/ie.css', 'screen, projection', 'IE');

    // @todo remove
    $this->headLink()->appendStylesheet('/css/layouts/default/layout.css', 'screen, projection');

    // set default meta
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

    // set default title if empty
    $title = $this->headTitle()->getValue();
    if (empty($title)) {
        $this->headTitle()->set(__('Welcome to MyProject!'));

	    // set prepend title
    	$this->headTitle()->prepend(__('MyProject'));
    }

    // set favicon
    $this->headLink(array('rel' => 'favicon', 'href' => '/favicon.ico'));

    // set default meta
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

    // display DocType
    echo $this->doctype() . "\n";
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headStyle(); ?>

</head>
<body>
    <div class="container">

        <div id="header">

            <div class="span-5">
                <h1><?php echo $this->escape(__('MyProject')); ?><h1>
            </div>

            <div class="clear"></div>

        </div>

        <div id="content">
            <?php echo $this->placeholder('Zend_Layout')->content; ?>
        </div>

        <div id="footer">
        </div>
    </div>
</body>
</html>
