<h1>Hello from Ajax</h1>
<h2>Ajax Request date is <?php echo date('Y-m-d H:i:s'); ?></h2>
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae rutrum
    justo. Morbi adipiscing consequat facilisis. Proin nunc nunc, condimentum vel
    sagittis sed, tempus eu ligula. Aliquam vitae elit erat. Proin rhoncus tempus
    dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a diam
    justo. Etiam blandit ligula id risus sollicitudin aliquam. Morbi in sapien dui.
    Mauris suscipit rutrum dui, nec molestie nulla tincidunt nec. Vivamus nisi dui,
    pulvinar eu molestie a, mattis ut lectus. Class aptent taciti sociosqu ad litora
    torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi
    tristique senectus et netus et malesuada fames ac turpis egestas. Donec eleifend
    elementum enim fringilla pellentesque. Suspendisse sit amet tincidunt libero.
    Sed sollicitudin risus vel orci semper consequat. Aenean lacus tortor, imperdiet
    id pellentesque eget, pretium vitae ipsum
</p>
