<script type="text/javascript">

// update widget elements
    widget.setTitle('Test Title update');
    widget.setIcon("http://cdn.netvibes.com/modules/uwa/icon.png");
    widget.setUnreadCount(1);
    widget.setSearchResultCount(2);

    var TabViewSample = {};

    widget.onLoad = function() {

      // init tab system
      if (typeof(TabViewSample.tabs) == "undefined") {


          var tabs = new UWA.Controls.TabView();

          TabViewSample.tabs = tabs;

          // Create tab items
          tabs.addTab("tab1", {text: "UWA Links", customInfo: "custom"});
          tabs.addTab("tab2", {text: "Grid Data"});
          tabs.addTab("tab3", {text: "E-Mail List"});
          tabs.addTab("tab4", {text: "Rich list "});
          tabs.addTab("tab5", {text: "Thumbs list"});
          tabs.addTab("tab6", {text: "Json"});
          tabs.addTab("tab7", {text: "Ajax"});
          tabs.addTab("tab8", {text: "Prefs"});
          tabs.addTab("tab9", {text: "Export"});

          // Put some content in tabs
          tabs.setContent("tab1", $('hello-content').innerHTML);
          tabs.setContent("tab2", $('griddata-content').innerHTML);
          tabs.setContent("tab3", $('emaillist-content').innerHTML);
          tabs.setContent("tab4", $('richlist-content').innerHTML);
          tabs.setContent("tab5", $('thumbist-content').innerHTML);
          tabs.setContent("tab6", $('json-content').innerHTML);
          tabs.setContent("tab7", $('ajax-content').innerHTML);
          tabs.setContent("tab8", $('prefs-content').innerHTML);
          tabs.setContent("tab9", $('export-content').innerHTML);

          // Register to activeTabChange event
          tabs.observe('activeTabChange', TabViewSample.onActiveTabChanged);

      } else {
          var tabs = TabViewSample.tabs;
      }

      // Restore saved active tab
      var activeTab = widget.getValue('activeTab');

      if (activeTab) {

          if (TabViewSample.tabs.selectedTab) {
              tabs.reload();
          } else {
              tabs.selectTab(activeTab);
          }

      } else {
          tabs.selectTab('tab1');
      }

      widget.setBody(TabViewSample.tabs.tabSet);
      widget.onResize();
    }

    TabViewSample.onActiveTabChanged = function(name, data) {

        var tabs = TabViewSample.tabs;

        // Save active tab
        widget.setValue("activeTab", name);

        if (name == 'tab6') {

            var onCompleteJson = function(json) {
                tabs.setContent(name, 'json date is:' + json.date);
            }

            UWA.Data.request('<?php echo MAIN_URL; ?>/example/uwa/jsoncallback', {
                method: 'get',
                type: 'json',
                proxy: 'ajax',
                onComplete: onCompleteJson.bind(this)
            });

        } else if (name == 'tab7') {

            var onCompleteAjax = function(html) {
                tabs.setContent(name, html);
            }

            UWA.Data.request('<?php echo MAIN_URL; ?>/example/uwa/ajaxcallback', {
                method: 'get',
                type: 'html',
                proxy: 'ajax',
                onComplete: onCompleteAjax.bind(this)
            });
        } else if (name == 'tab8') {

            html = '<h1>Preference values</h1>'
            + '<ul style="padding: 5px;">'
                + '<li>my_text: ' + widget.getValue('my_text') + "</li>"
                + '<li>my_text: ' + widget.getValue('pass') + "</li>"
                + '<li>my_checkbox: ' + widget.getValue('my_checkbox') + "</li>"
                + '<li>my_range: ' + widget.getValue('my_range') + "</li>"
                + '</ul>'

            tabs.setContent(name, html);
        }

        widget.onResize();
    }

    var resized = 0;
    var OriginalTitle = widget.getTitle();

    widget.onResize = function() {
        widget.setTitle(OriginalTitle + '(resized:' + resized++ + ')' );
    }

</script>

<div style="display:none">

    <div id="hello-content" class="tab-content">
        <ul>
            <li><a href="http://netvibes.org/">UWA Website</a></li>
            <li><a href="http://dev.netvibes.com/">Developer UWA Website</a></li>
            <li><a href="http://netvibes.org/specs/uwa/current-work/">specs Universal Widget API (UWA) 1.2 </a></li>
        </ul>
    </div>

    <div id="griddata-content" class="tab-content">

        <table class="nv-datagrid">
            <thead>
                <tr>
                    <th>col 0</th>
                    <th>col 1</th>
                    <th>column 2</th>
                </tr>
            </thead>

            <tfoot>
                <tr>
                    <td>footer 1</td>
                    <td>footer 2</td>
                    <td>footer 3</td>
                </tr>
            </tfoot>

            <tbody>
                <tr>
                    <td>1</td>
                    <td>line 1</td>
                    <td>line number 1</td>
                </tr>

                <tr>
                    <td>2</td>
                    <td>line 2</td>
                    <td>line number 2</td>
                </tr>

                <tr>
                    <td>3</td>
                    <td>col 1</td>
                    <td>line number 3</td>
                </tr>
            </tbody>
        </table>

    </div>

    <div id="emaillist-content" class="tab-content">

        <dl class="nv-emailList">

            <dt class="unread">
                <a href="#" onclick="return false" title="Read e-mail">
                <strong class="sender">Sender</strong> - My e-mail subject #1</a>
            </dt>

            <dd>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus condimentum. Phasellus auctor.</p>
            </dd>

            <dt class="read">
                <a href="#" onclick="return false" title="Read e-mail">
                <strong class="sender">Sender</strong> - My e-mail subject #2</a>
            </dt>

            <dd>
                <p>Donec odio turpis, vulputate non, tristique a, placerat non, nunc.</p>
            </dd>

            <dt class="read">
                <a href="#" onclick="return false" title="Read e-mail">
                <span class="sender">Sender</span> - My e-mail subject #3</a>
            </dt>

            <dd>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus condimentum.</p>
            </dd>
        </dl>

    </div>


    <div id="richlist-content">

        <div class="nv-richList">
            <div class="item even">
                <h3><a href="#">Item #1</a></h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                    Phasellus condimentum.
                </p>
            </div>

            <div class="item odd">
                <h3><a href="#">Item #2</a></h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                    Phasellus condimentum.
                </p>
            </div>

            <div class="item even">
                <h3><a href="#">Item #3</a></h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                    Phasellus condimentum.
                </p>
            </div>
        </div>

    </div>

    <div id="thumbist-content">

        <div class="nv-thumbnailedList">
            <div class="item even">
                <a href="#"><img src="<?php echo MAIN_URL; ?>/images/layouts/uwa/uwa-screenshot.png" alt="" class="thumbnail" /></a>
                <h3><a href="#">Item #1</a></h3>
                <p>
                Lorem ipsum dolor sit amet,
                    consectetuer adipiscing elit. Phasellus
                </p>
            </div>

            <div class="item odd">
                <a href="#"><img src="<?php echo MAIN_URL; ?>/images/layouts/uwa/uwa-screenshot.png" alt="" class="thumbnail" /></a>
                <h3><a href="#">Item #2</a></h3>
                <p>Short text to test flotting picture behaviour.</p>
            </div>

            <div class="item even">
                <a href="#"><img src="<?php echo MAIN_URL; ?>/images/layouts/uwa/uwa-screenshot.png" alt="" class="thumbnail" /></a>
                <h3><a href="#">Item #3</a></h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer
                    adipiscing elit. Maecenas vitae elit at sem dapibus iaculis.
                    Nullam nec ipsum. Fusce gravida, magna nec tincidunt laoreet,
                    est lorem porttitor nunc, non suscipit mauris turpis non
                    turpis. Class aptent taciti sociosqu ad litora torquent per
                    conubia nostra, per inceptos hymenaeos. Duis nec metus. Lorem
                    ipsum dolor sit amet, consectetuer adipiscing elit. Sed
                    gravida aliquam pede.
                </p>
            </div>
        </div>

    </div>

    <div id="json-content">
        Loading...
    </div>

    <div id="ajax-content">
        Loading...
    </div>

    <div id="prefs-content">
        Loading...
    </div>

    <div id="export-content">
        <?php
            $uwaServerUrl = 'http://uwa.service.japanim.fr';
            $uwaWidgetUrl = MAIN_URL . $_SERVER['REQUEST_URI'];
        ?>

        <h2>Stable</h2>
        <ul>
            <li><a target="_blank" href="<?php echo $this->uwaExportLink('netvibes', $uwaWidgetUrl, $uwaServerUrl); ?>">Netvibes</a></li>
            <li><a target="_blank" href="<?php echo $this->uwaExportLink('google', $uwaWidgetUrl, $uwaServerUrl); ?>">iGoogle</a></li>
            <li><a target="_blank" href="<?php echo $this->uwaExportLink('dashboard', $uwaWidgetUrl, $uwaServerUrl); ?>">Dashboard</a></li>
            <li><a target="_blank" href="<?php echo $this->uwaExportLink('screenlets', $uwaWidgetUrl, $uwaServerUrl); ?>">Screenlets</a></li>
            <li><a target="_blank" href="<?php echo $this->uwaExportLink('blogger', $uwaWidgetUrl, $uwaServerUrl); ?>">Blogger</a></li>
            <li><a target="_blank" href="<?php echo $this->uwaExportLink('live', $uwaWidgetUrl, $uwaServerUrl); ?>">Live</a></li>
            <li><a target="_blank" href="<?php echo $this->uwaExportLink('opera', $uwaWidgetUrl, $uwaServerUrl); ?>">Opera</a></li>
            <li>
                <a target="_blank" href="<?php echo $this->uwaExportLink('frame', $uwaWidgetUrl, $uwaServerUrl, array('id' => md5($this->url()))); ?>">Iframe</a>
                (
                    <a target="_blank" href="<?php echo $this->uwaExportLink('frame', $uwaWidgetUrl, $uwaServerUrl, array('id' => md5($this->url()), 'header' => 1)); ?>">with header</a>
                    - <a target="_blank" href="<?php echo $this->uwaExportLink('frame', $uwaWidgetUrl, $uwaServerUrl, array('id' => md5($this->url()), 'header' => 1, 'chromeColor' => 'orange')); ?>">with header color</a>
                    - <a target="_blank" href="<?php echo $this->uwaExportLink('frame', $uwaWidgetUrl, $uwaServerUrl, array('id' => md5($this->url()), 'header' => 1, 'status' => 0)); ?>">without status</a>
                )
            </li>
        </ul>

        <h2>Unstable</h2>
        <ul>
            <li><a target="_blank" href="<?php echo $this->uwaExportLink('jil', $uwaWidgetUrl, $uwaServerUrl); ?>">Jil/Ophone</a> (Work in progress)</li>
            <li><a target="_blank" href="<?php echo $this->uwaExportLink('vista', $uwaWidgetUrl, $uwaServerUrl); ?>">Windows Vista/SEVEN</a> (Work in progress)</li>
        </ul>
    </div>
</div>
<p>
    Loading...
</p>
