<script type="text/javascript">

    widget.setTitle('Test Title update');
    widget.setIcon("http://cdn.netvibes.com/modules/uwa/icon.png");
    widget.setUnreadCount(1);
    widget.setSearchResultCount(2);

    widget.onResize = function() {
        //alert('resize');
    }

</script>
<?php

	$uwaServerUrl = 'http://uwa.service.japanim.fr';
?>
<p>
    <ul>
		<li><a target="_blank" href="<?php echo $this->uwaExportLink('netvibes', 'http://basezf.japanim.fr/example/uwa/', $uwaServerUrl); ?>">Netvibes</a></li>
		<li><a target="_blank" href="<?php echo $this->uwaExportLink('google', 'http://basezf.japanim.fr/example/uwa/', $uwaServerUrl); ?>">iGoogle</a></li>
		<li><a target="_blank" href="<?php echo $this->uwaExportLink('dashboard', 'http://basezf.japanim.fr/example/uwa/', $uwaServerUrl); ?>">Dashboard</a></li>
		<li><a target="_blank" href="<?php echo $this->uwaExportLink('opera', 'http://basezf.japanim.fr/example/uwa/', $uwaServerUrl); ?>">Opera</a></li>
	</ul>
</p>

