<div id="main" class="l-border r-border span-15">

    <h1 id="intro"><a href="#intro"><?php echo $this->escape(__('Fancy Select')); ?></a></h1>

    <h2 id="Features"><a href="#Features"><?php echo $this->escape(__('Features')); ?></a></h2>

    <h2 id="Examples"><a href="#Examples"><?php echo $this->escape(__('Examples')); ?></a></h2>

    <?php echo $this->form; ?>

</div>

<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#Title"><?php echo $this->escape(__('Fancy Select')); ?></a></h4>
    <div class="menu-item"><a href="#Features"><?php echo $this->escape(__('Features')); ?></a></div>
    <div class="menu-item"><a href="#Examples"><?php echo $this->escape(__('Examples')); ?></a></div>
</div>
