<?php
/**
 * Error layout for MyProject
 *
 * @category   MyProject
 * @package    MyProject_App_Layouts
 * @copyright  Copyright (c) 2008 MyProject
 * @author     Harold Thetiot (hthetiot)
 */

    // display error for json callback
    if ($this->isJson) {

        $json = array(
            'error' => $this->message,
        );

        echo json_encode($json);

    // display error for ajax callback
    } else if ($this->isAjax) {

        echo '<script type="text/javascript">';
        echo '/*' . $this->message . '*/';
        echo '</script>';

    // display error for HTML callback
    } else {

        echo '<html>';
        echo '<body>';
        echo $this->placeholder('Zend_Layout')->content;
        echo '</body>';
        echo '</html>';
    }

