<div id="main" class="l-border span-18">

    <h1><a href="#"><?php echo $this->escape(__('BaseZF Examples')); ?></a></h1>

    <h2><a href="#">What is BaseZF ?</a></h2>

    <p>
        BaseZF is a <a href="#">Zend Framework</a> Implementation, it provide to the native Zend Framework some missing classes and functions to implement
        any website with standart features.
    </p>

    <p>
        BaseZF include allso some frontend part to make CSS and Javascript, it using <a href="#">Mootools</a> JS Framework and <a href="#">BluePrint</a> CSS Framework.
    </p>

    <p>
        BaseZF is a good start to begin a site from scratch it provide to you guidelines and structure to maintain and make evolve your website
        and respect standart as the same time.
    </p>

    <h2><a href="#">What I can found in this module ?</a></h2>

    <p>
        This module contains examples and documentation of features available in BaseZF Zend Framework Implementation.
    </p>

</div>

