<div id="main" class="l-border r-border span-15">

    <h1 id="intro"><a href="#Title">Makefile</a></h1>

    <p class="description">
        You can use the Makefile scripts at the root of projects with following arguments
        to make fast and simple automatised tasks.
    </p>

    <h2 id="usage"><a href="#usage">Usage</a></h2>
    <p class="description">

<?php

    $source = array(
        '# cd /myproject/',
        '# make <callbacks>',
    );
    echo $this->GeSHi(implode("\n", $source), 'bash');
?>

    </p>

    <h2 id="callbacks"><a href="#callbacks">Callbacks</a></h2>

    <h3 id="syntax"><a href="#syntax">doc</a></h3>
    <p class="description">
        Generate the doxygen doc on /doc/ directory from config file available in /etc/doxygen.conf
        You can see this documentation online at <a href="/debug/doc">/debug/doc</a>.
    </p>

    <h3 id="syntax"><a href="#syntax">syntax</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="syntax-fast"><a href="#syntax-fast">syntax-fast</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="test"><a href="#test">test</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="test-report"><a href="#test-report">test-report</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="config"><a href="#config">config</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="locale"><a href="#locale">locale</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="locale-template"><a href="#locale-template">locale-template</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="locale-update"><a href="#locale-update">locale-update</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="locale-deploy"><a href="#locale-deploy">locale-deploy</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="locale-deploy-fuzzy"><a href="#locale-deploy-fuzzy">locale-deploy-fuzzy</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="locale-translate-google"><a href="#locale-translate-google">locale-translate-google</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="locale-clean"><a href="#locale-clean">locale-clean</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="static-pack"><a href="#static-pack">static-pack</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="static-pack-css"><a href="#static-pack-css">static-pack-css</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="static-pack-js"><a href="#static-pack-js">static-pack-js</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="log-clean"><a href="#log-clean">log-clean</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="log-archive"><a href="#log-archive">log-archive</a></h3>

    <p class="description">
        @todo
    </p>

    <h3 id="clean"><a href="#clean">clean</a></h3>

    <p class="description">
        @todo
    </p>

</div>


<div id="menu" class="span-5 last">

    <h4 class="menu-item"><a href="#Title">Makefile</a></h4>
    <div class="menu-item"><a href="#syntax">Syntax</a></div>

    <h4 class="menu-item"><a href="#callbacks">Callbacks</a></h4>
    <div class="menu-item"><a href="#syntax">syntax</a></div>
    <div class="menu-item"><a href="#syntax-fast">syntax-fast</a></div>
    <div class="menu-item"><a href="#test">test</a></div>
    <div class="menu-item"><a href="#test-report">test-report</a></div>
    <div class="menu-item"><a href="#config">config</a></div>
    <div class="menu-item"><a href="#locale">locale</a></div>
    <div class="menu-item"><a href="#locale-template">locale-template</a></div>
    <div class="menu-item"><a href="#locale-update">locale-update</a></div>
    <div class="menu-item"><a href="#locale-deploy">locale-deploy</a></div>
    <div class="menu-item"><a href="#locale-deploy-fuzzy">locale-deploy-fuzzy</a></div>
    <div class="menu-item"><a href="#locale-translate-google">locale-translate-google</a></div>
    <div class="menu-item"><a href="#locale-clean">locale-clean</a></div>
    <div class="menu-item"><a href="#static-pack">static-pack</a></div>
    <div class="menu-item"><a href="#static-pack-css">static-pack-css</a></div>
    <div class="menu-item"><a href="#static-pack-js">static-pack-js</a></div>
    <div class="menu-item"><a href="#log-clean">log-clean</a></div>
    <div class="menu-item"><a href="#log-archive">log-archive</a></div>
    <div class="menu-item"><a href="#clean">clean</a></div>
</div>

