<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">Title</a></h1>

    <p class="description">
        Bla bla...
    </p>

    <h2 id="Section"><a href="#Section">Section</a></h2>
    <h3 id="">Sub Sections</h3>

    <p class="description">
        Bla bla...
    </p>

</div>

<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#Title">Title</a></h4>
    <div class="menu-item"><a href="#Section">Section</a></div>
</div>
