<div id="main" class="l-border r-border span-15">

    <h1 id="intro"><a href="#Title">Simple XMLRPC</a></h1>
    <p class="description">
        @todo
    </p>

    <h2 id="Syntax"><a href="#Syntax">Syntax</a></h2>
    <p class="description">
        @todo
    </p>

    <h2 id="Examples"><a href="#Examples">Examples</a></h2>
    <p class="description">
        @todo
    </p>

</div>


<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#Title">Debug</a></h4>
    <div class="menu-item"><a href="#Syntax">Syntax</a></div>
    <div class="menu-item"><a href="#Examples">Examples</a></div>
</div>

