<?php
/**
 * Uwa layout for MyProject
 *
 * @category   MyProject
 * @package    MyProject_App_Layouts
 * @copyright  Copyright (c) 2008 MyProject
 * @author     Harold Thetiot (hthetiot)
 */

    // set default title if empty
    $this->headTitle()->set($this->widget->title);

    // add default styleSheet
    $this->headLink()->appendStylesheet('http://uwa.service.japanim.fr/css/uwa-standalone.css');

    // add default scripts
    //$this->headScript()->appendFile('http://www.netvibes.com/js/UWA/load.js.php?env=Standalone');
    $this->headScript()->appendFile('http://uwa.service.japanim.fr/js/c/UWA_Standalone.js');
    //$this->headScript()->appendFile('http://uwa.service.japanim.fr/js/c/UWA_Standalone_Mootools.js');

    // add tools
    $this->headScript()->appendFile('http://cdn.netvibes.com/js/c/UWA_Controls_TabView.js?v=preview3');

    // set favicon
    $this->headLink(array('rel' => 'favicon', 'href' =>  $this->currentHost . '/favicon.ico', 'type' => 'image/x-icon'));

    // add default meta
    foreach($this->widget->metas as $name => $value) {
        if (!is_null($value)) {
            $this->headMeta()->appendName($name, $value);
        }
    }

    // extract widget data
    $widgetSource = $this->placeholder('Zend_Layout')->content;
    $pattern = '|(<script[^>]*>([\s\S]*?)<\/script>)?(.*)?|ims';
    preg_match($pattern, $widgetSource, $matches);

    $widgetScript = isset($matches[2]) ? $matches[2] : null;
    $widgetBody = isset($matches[3]) ? $matches[3] : null;

    // render
    echo '<?xml version="1.0" encoding="utf-8"?>';

    // display DocType
    echo $this->doctype() . "\n";

?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:widget="http://www.netvibes.com/ns/">
    <head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headTitle(); ?>
    <link rel="icon" type="image/x-icon" href="<?php echo $this->currentHost ?>/favicon.ico" />
    <?php echo $this->uwaWidgetPreferences($this->widget->preferences); ?>
    <script type="text/javascript">
        <?php echo $widgetScript; ?>
    </script>
    </head>
    <body>
        <?php echo $widgetBody; ?>
    </body>
</html>

