<div id="main" class="l-border r-border span-15">

    <h1 id="intro"><a href="#Title">Archive</a></h1>

    <p class="description">
        Compress and Extract archive on common format without any binary
        or PEAR Extention.
    </p>

    <h2 id="syntax"><a href="#syntax">Syntax</a></h2>

    <p class="description">
        @todo
    </p>

    <h2 id="syntax"><a href="#functions">Functions</a></h2>

    <p class="description">
        @todo
    </p>

</div>


<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#Title">Archive</a></h4>
    <div class="menu-item"><a href="#syntax">Syntax</a></div>
    <div class="menu-item"><a href="#functions">Functions</a></div>
</div>

