<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">Controller Abstract</a></h1>

    <p class="description">
        Bla bla...
    </p>

    <h2 id="Section"><a href="#initModule">Function: initModule</a></h2>

    <p class="description">
        Bla bla...
    </p>

</div>

<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#Title">Controller Abstract</a></h4>
    <div class="menu-item"><a href="#initModule">initModule</a></div>
    <div class="menu-item"><a href="#initController">initController</a></div>

    <div class="menu-item"><a href="#_setLayout">_setLayout</a></div>

    <div class="menu-item"><a href="#_makeHtml">_makeHtml</a></div>

    <div class="menu-item"><a href="#_makeAjax">_makeAjax</a></div>
    <div class="menu-item"><a href="#_makeAjaxHtml">_makeAjaxHtml</a></div>
    <div class="menu-item"><a href="#_addAjax">_addAjax</a></div>

    <div class="menu-item"><a href="#_makeJson">_makeJson</a></div>
    <div class="menu-item"><a href="#_addJson">_addJson</a></div>
    <div class="menu-item"><a href="#_setJson">_setJson</a></div>
</div>
