<div id="main" class="l-border r-border span-15">

    <h1 id="intro"><a href="#intro">DbItem</a></h1>

    <p class="description">
        Bla bla...
    </p>

    <h2 id=""><a href="#">Function: GetInstance</a></h2>
    <h2 id=""><a href="#">Function: GetId</a></h2>
    <h2 id=""><a href="#">Function: GetExtendedId</a></h2>
    <h2 id=""><a href="#">Function: GetDbItemExtendedId</a></h2>
    <h2 id=""><a href="#">Function: SetRealTime</a></h2>
    <h2 id=""><a href="#">Function: IsRealTime</a></h2>
    <h2 id=""><a href="#">Function: IsDeleted</a></h2>
    <h2 id=""><a href="#">Function: IsLoaded</a></h2>
    <h2 id=""><a href="#">Function: IsModified</a></h2>
    <h2 id=""><a href="#">Function: GetProperty</a></h2>
    <h2 id=""><a href="#">Function: GetProperties</a></h2>
    <h2 id=""><a href="#">Function: SetProperty</a></h2>
    <h2 id=""><a href="#">Function: SetProperties</a></h2>
    <h2 id=""><a href="#">Function: SetVirtualProperty</a></h2>
    <h2 id=""><a href="#">Function: ResetProperty</a></h2>
    <h2 id=""><a href="#">Function: Insert</a></h2>
    <h2 id=""><a href="#">Function: Update</a></h2>
    <h2 id=""><a href="#">Function: Delete</a></h2>
    <h2 id=""><a href="#">Function: IsEqual</a></h2>

    <h1 id="intro"><a href="#intro">DbCollection</a></h1>

</div>


<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#intro">DbItem</a></h4>
    <div class="menu-item"><a href="#">GetInstance</a></div>
    <div class="menu-item"><a href="#">GetId</a></div>
    <div class="menu-item"><a href="#">GetExtendedId</a></div>
    <div class="menu-item"><a href="#">GetDbItemExtendedId</a></div>
    <div class="menu-item"><a href="#">SetRealTime</a></div>
    <div class="menu-item"><a href="#">IsRealTime</a></div>
    <div class="menu-item"><a href="#">IsDeleted</a></div>
    <div class="menu-item"><a href="#">IsLoaded</a></div>
    <div class="menu-item"><a href="#">IsModified</a></div>
    <div class="menu-item"><a href="#">GetProperty</a></div>
    <div class="menu-item"><a href="#">GetProperties</a></div>
    <div class="menu-item"><a href="#">SetProperty</a></div>
    <div class="menu-item"><a href="#">SetProperties</a></div>
    <div class="menu-item"><a href="#">SetVirtualProperty</a></div>
    <div class="menu-item"><a href="#">ResetProperty</a></div>
    <div class="menu-item"><a href="#">Insert</a></div>
    <div class="menu-item"><a href="#">Update</a></div>
    <div class="menu-item"><a href="#">Delete</a></div>
    <div class="menu-item"><a href="#">IsEqual</a></div>

    <h4 class="menu-item"><a href="#intro">DbCollection</a></h4>
</div>

