<div id="main" class="l-border r-border span-15">

    <h1 id="intro"><a href="#Title">DbSearch</a></h1>

    <p class="description">
        @todo
    </p>

    <h2 id="syntax"><a href="#syntax">Syntax</a></h2>

    <p class="description">
        @todo
    </p>

    <h2 id="syntax"><a href="#syntax">Examples</a></h2>

    <p class="description">
        @todo
    </p>

</div>


<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#Title">DbSearch</a></h4>
    <div class="menu-item"><a href="#syntax">Syntax</a></div>
    <div class="menu-item"><a href="#examples">Examples</a></div>
</div>

