<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">Error Handler</a></h1>

    <p class="description">
        @todo
    </p>

    <h2 id="Section"><a href="#Section">Example</a></h2>

    <p class="description">
        This an example of error handlings for an undefined variable.
    </p>

    <iframe height="600" src="/example/BaseZF/error?error=1"></iframe>

</div>

<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#Title">Title</a></h4>
    <div class="menu-item"><a href="#Section">Section</a></div>
</div>
