<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">Notify</a></h1>

    <p class="description">
        Bla bla...
    </p>

    <h2 id=""><a href="#">Function: getInstance</a></h2>
    <h2 id=""><a href="#">Function: set</a></h2>
    <h2 id=""><a href="#">Function: get</a></h2>
    <h2 id=""><a href="#">Function: getAll</a></h2>
    <h2 id=""><a href="#">Function: delete</a></h2>
    <h2 id=""><a href="#">Function: isExist</a></h2>

</div>

<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#Title">Title</a></h4>
    <div class="menu-item"><a href="#Section">Section</a></div>
</div>
