<?php
/**
 * Example layout for BasZF
 *
 * @category   BasZF_Layouts
 * @package    BasZF
 * @copyright  Copyright (c) 2008 BasZF
 * @author     Harold Thétiot (hthetiot)
 */

    //
    // CSS stuff
    //

    // add blueprint stylesheet
    $this->headLink()->appendStylesheet('/css/lib/blueprint/screen.css', 'screen, projection');
    $this->headLink()->appendStylesheet('/css/lib/blueprint/print.css', 'print');
    $this->headLink()->appendStylesheet('/css/lib/blueprint/ie.css', 'screen, projection', 'IE');

    // element files (include in lib.css)
    {
        // add basezf elements
        $this->headLink()->appendStylesheet('/css/lib/basezf/elements/formLayout.css', 'screen, projection');
		$this->headLink()->appendStylesheet('/css/lib/basezf/elements/formFancySelect.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/css/lib/basezf/elements/fancyMenu.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/css/lib/basezf/elements/fancyButton.css', 'screen, projection');
	}

	// set Layout stylesheet at the end to overide needed
    $this->headLink()->appendStylesheet('/css/layouts/example/layout.css', 'screen, projection');

    //
    // JS stuff
    //

    // add motools JS framework
	/*
    $this->headScript()->appendFile('http://www.google.com/jsapi');
    $this->headScript()->appendScript('google.load("mootools", "1.2.1");');
    */

	$this->headScript()->appendFile('/js/lib/mootools-1.2.1-core.js');
    $this->headScript()->appendFile('/js/lib/mootools-1.2-more.js');

    // add BaseZF JS framework (include in main.js)
    {
        $this->headScript()->appendFile('/js/lib/basezf/BaseZF.js');
        $this->headScript()->appendFile('/js/lib/basezf/Class/Helper.js');
        $this->headScript()->appendFile('/js/lib/basezf/Helper/AjaxLink.js');
        $this->headScript()->appendFile('/js/lib/basezf/Helper/FormFancySelect.js');
        $this->headScript()->appendFile('/js/lib/basezf/Helper/FormAjaxValidate.js');
    }

    // motools plugins files (include in lib.js and lib.css)
    {
        // auto completer
        $this->headScript()->appendFile('/js/lib/motools-plugins/Autocompleter/Autocompleter.js');
        $this->headScript()->appendFile('/js/lib/motools-plugins/Autocompleter/Autocompleter.Request.js');
        $this->headScript()->appendFile('/js/lib/motools-plugins/Autocompleter/Observer.js');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/Autocompleter/Autocompleter.css', 'screen, projection');

        // lightbox
        $this->headScript()->appendFile('/js/lib/motools-plugins/SqueezeBox/SqueezeBox.js');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/SqueezeBox/SqueezeBox.css', 'screen, projection');

        // Calendar
        $this->headScript()->appendFile('/js/lib/motools-plugins/Calendar/calendar.js');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/Calendar/default/calendar.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/Calendar/i-heart-ny/calendar.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/Calendar/dashboard/calendar.css', 'screen, projection');
    }

    //
    // Others
    //

    // set default title if empty
    $title = $this->headTitle()->getValue();
    if (empty($title)) {
        $this->headTitle()->set(__('Examples module'));

	    // set prepend title
    	$this->headTitle()->prepend(__('BaseZF') . ' - ');
    }

    // set default meta
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

    // display DocType
    echo $this->doctype() . "\n";
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headStyle(); ?>

</head>
<body>
    <div class="container">

        <div id="header">

        </div>

        <div id="main-menu" class="span-4">
            <?php
                echo $this->navigation();
            ?>
        </div>

        <?php echo $this->placeholder('Zend_Layout')->content; ?>

        <div id="footer" class="column clear span-24">
            <p>
              This documentation is released under a <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Attribution-NonCommercial-ShareAlike 3.0</a>
              License.
            </p>
        </div>
    </div>

    <div id="loading">Loading...</div>

</body>
</html>
