<?php
/**
 * Example layout for MyProject
 *
 * @category   MyProject
 * @package    MyProject_App_Layouts
 * @copyright  Copyright (c) 2008 MyProject
 * @author     Harold Thetiot (hthetiot)
 */
    //
    // CSS stuff
    //

    // add blueprint stylesheet
    $this->headLink()->appendStylesheet('/css/lib/blueprint/blueprint/screen.css', 'screen, projection');
    $this->headLink()->appendStylesheet('/css/lib/blueprint/blueprint/print.css', 'print');
    $this->headLink()->appendStylesheet('/css/lib/blueprint/blueprint/ie.css', 'screen, projection', 'IE');

    // element files (include in lib.css)
    {
        // add basezf elements
        $this->headLink()->appendStylesheet('/css/lib/basezf/elements/formLayout.css', 'screen, projection');
		$this->headLink()->appendStylesheet('/css/lib/basezf/elements/formFancySelect.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/css/lib/basezf/elements/fancyMenu.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/css/lib/basezf/elements/fancyButton.css', 'screen, projection');
	}

	// set Layout stylesheet at the end to overide needed
    $this->headLink()->appendStylesheet('/css/layouts/example/layout.css', 'screen, projection');

    //
    // JS stuff
    //

    // add motools JS framework
	/*
    $this->headScript()->appendFile('http://www.google.com/jsapi');
    $this->headScript()->appendScript('google.load("mootools", "1.2.2");');
    */

	$this->headScript()->appendFile('/js/lib/mootools-core.js');
    $this->headScript()->appendFile('/js/lib/mootools-more.js');

    // add BaseZF JS framework (include in main.js)
    {
        $this->headScript()->appendFile('/js/lib/basezf/BaseZF.js');
        $this->headScript()->appendFile('/js/lib/basezf/Helper/Abstract.js');
        $this->headScript()->appendFile('/js/lib/basezf/Helper/AjaxAbstract.js');
        $this->headScript()->appendFile('/js/lib/basezf/Helper/AjaxLink.js');
        $this->headScript()->appendFile('/js/lib/basezf/Helper/AjaxForm.js');
        $this->headScript()->appendFile('/js/lib/basezf/Helper/FormFancySelect.js');
        $this->headScript()->appendFile('/js/lib/basezf/Helper/FormAjaxValidate.js');
    }

    // motools plugins files (include in lib.js and lib.css)
    {
        // auto completer
        $this->headScript()->appendFile('/js/lib/motools-plugins/Autocompleter/Autocompleter.js');
        $this->headScript()->appendFile('/js/lib/motools-plugins/Autocompleter/Autocompleter.Request.js');
        $this->headScript()->appendFile('/js/lib/motools-plugins/Autocompleter/Observer.js');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/Autocompleter/Autocompleter.css', 'screen, projection');

        // lightbox
        $this->headScript()->appendFile('/js/lib/motools-plugins/SqueezeBox/SqueezeBox.js');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/SqueezeBox/SqueezeBox.css', 'screen, projection');

        // Calendar
        $this->headScript()->appendFile('/js/lib/motools-plugins/Calendar/calendar.js');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/Calendar/default/calendar.css', 'screen, projection');
        /*
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/Calendar/i-heart-ny/calendar.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/Calendar/dashboard/calendar.css', 'screen, projection');
        */

        // Progress bar
        /*
        $this->headScript()->appendFile('/js/lib/motools-plugins/dwProgressBar/dwProgressBar.js');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/dwProgressBar/dwProgressBar.css', 'screen, projection');
        */
    }

    // Firebug-lite
    //$this->headScript()->appendFile('http://getfirebug.com/releases/lite/1.2/firebug-lite-compressed.js');

    //
    // Others
    //

    // set default title if empty
    $title = $this->headTitle()->getValue();
    if (empty($title)) {
        $this->headTitle()->set(__('Examples module'));

	    // set prepend title
    	$this->headTitle()->prepend(__('BaseZF'));
    }

    // set favicon
    $this->headLink(array('rel' => 'favicon', 'href' => '/favicon.ico'));

    // set default meta
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

    // display DocType
    echo $this->doctype() . "\n";

?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headStyle(); ?>
</head>
<body>
    <div class="container">

        <div id="header">

        </div>

        <div id="main-menu" class="span-4">
            <?php echo $this->exampleNavigation(); ?>
        </div>

        <?php echo $this->placeholder('Zend_Layout')->content; ?>

        <div id="footer" class="column clear span-24">

            <p id="powerby">
                <a href="http://framework.zend.com/" onclick="window.open(this.href); return false;">
                    <img width="127" height="25" alt="Powered by the Zend Framework" src="/images/layouts/example/powered-by-zf.png"/>
                </a>

                <a href="http://validator.w3.org/check?uri=<?php echo urlencode(MAIN_URL . $_SERVER['REQUEST_URI']); ?>" onclick="window.open(this.href); return false;">
                    <img src="/images/layouts/example/w3c-xhtml.gif" alt="Valid XHTML 1.0 Strict" height="25" width="88" />
                </a>
            </p>

            <p id="license">
                This documentation is released under a <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/" onclick="window.open(this.href); return false;">Attribution-NonCommercial-ShareAlike 3.0</a> License.
            </p>

        </div>
    </div>

    <div id="loading">Loading...</div>
</body>
</html>
