<?php
/**
 * Example layout for BasZF
 *
 * @category   BasZF_Layouts
 * @package    BasZF
 * @copyright  Copyright (c) 2008 BasZF
 * @author     Harold Thétiot (hthetiot)
 */

    $this->headLink()->enablePacks(CONFIG_STATIC_PACK_CSS);
    $this->headLink()->setPrefixSrc(CDN_URL_CSS);

    $this->headScript()->enablePacks(CONFIG_STATIC_PACK_JS);
    $this->headScript()->setPrefixSrc(CDN_URL_JS);

    //
    // CSS stuff
    //

    // add blueprint stylesheet
    $this->headLink()->appendStylesheet('/css/lib/blueprint/screen.css', 'screen, projection');
    $this->headLink()->appendStylesheet('/css/lib/blueprint/print.css', 'print');
    $this->headLink()->appendStylesheet('/css/lib/blueprint/ie.css', 'screen, projection', 'IE');

    // set Layout stylesheet
    $this->headLink()->appendStylesheet('/css/layouts/example/layout.css', 'screen, projection');

    // element files (include in lib.css)
    {
        // add basezf elements
        $this->headLink()->appendStylesheet('/css/lib/basezf/elements/formLayout.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/css/lib/basezf/elements/fancyMenu.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/css/lib/basezf/elements/fancyButton.css', 'screen, projection');

        // add blueprint plugins stylesheet
        $this->headLink()->appendStylesheet('/css/lib/blueprint/plugins/fancy-type/screen.css', 'screen, projection');
        $this->headLink()->appendStylesheet('/css/lib/blueprint/plugins/sprites/sprite.css', 'screen, projection');
    }

    //
    // JS stuff
    //

    // add motools JS framework
    $this->headScript()->appendFile('http://www.google.com/jsapi?key=ABQIAAAAuno_MXfCpvDp_wlCZ6suSxT2AqkUG44FzJpmmcTlDpPqEtDyIhQA9Dn6ktK0oSoj_F88pZO-OMNkmA');
    $this->headScript()->appendScript('google.load("mootools", "1.2.1");');
    /*
    $this->headScript()->appendFile('/js/lib/mootools-1.2.1-core.js');
    $this->headScript()->appendFile('/js/lib/mootools-1.2-more.js');
    */

    // add BaseZF JS framework (include in main.js)
    {
        $this->headScript()->appendFile('/js/BaseZF/BaseZF.js');
        $this->headScript()->appendFile('/js/BaseZF/Class/Ajax.js');
        $this->headScript()->appendFile('/js/BaseZF/Class/Helper.js');
        $this->headScript()->appendFile('/js/BaseZF/Helper/AjaxLink.js');
        $this->headScript()->appendFile('/js/BaseZF/Helper/FormSelectMass.js');
    }

    // motools plugins files (include in lib.js and lib.css)
    {
        // auto completer
        $this->headScript()->appendFile('/js/lib/motools-plugins/Autocompleter/Autocompleter.js');
        $this->headScript()->appendFile('/js/lib/motools-plugins/Autocompleter/Autocompleter.Request.js');
        $this->headScript()->appendFile('/js/lib/motools-plugins/Autocompleter/Observer.js');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/Autocompleter/Autocompleter.css', 'screen, projection');

        // lightbox
        $this->headScript()->appendFile('/js/lib/motools-plugins/SqueezeBox/SqueezeBox.js');
        $this->headLink()->appendStylesheet('/js/lib/motools-plugins/SqueezeBox/SqueezeBox.css', 'screen, projection');
    }

    //
    // Others
    //

    // set default meta
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

    // display DocType
    echo $this->doctype() . "\n";
?>
<html>
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headStyle(); ?>

</head>
<body>
    <div class="container">

        <div id="header">

        </div>

        <div id="main-menu" class="span-4">
            <?php
                echo $this->navigation();
            ?>
        </div>

        <?php echo $this->placeholder('Zend_Layout')->content; ?>

        <div id="footer" class="column clear span-24">
            <p>
              This documentation is released under a <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Attribution-NonCommercial-ShareAlike 3.0</a>
              License.
            </p>
        </div>
    </div>

    <div id="loading">Loading...</div>

</body>
</html>
