<h1>An error occurred</h1>
<h2><?= $this->message ?></h2>


    <h3>Exception information: </h3>
    <p>
        <b>Name:</b> <?php echo get_class($this->exception) ?>
    </p>
    <p>
        <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?></pre>

    <h3>Request Parameters:</h3>
    <pre><?php var_dump($this->request->getParams()) ?></pre>


