<div id="main" class="l-border r-border span-15">

    <h1 id="intro"><a href="#intro">What?</a></h1>

    <p class="description">
        Bla bla...
    </p>

    <h2 id="syntax"><a href="#syntax"></a></h2>

</div>


<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#intro">Ajax Link</a></h4>
    <div class="menu-item"><a href="#syntax">Syntax</a></div>
    <div class="menu-item"><a href="#examples">Examples</a></div>
</div>

