<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">Ajax Form</a></h1>

    <h2 id="Features"><a href="#Features">Features</a></h2>

    <ul>
        <li>Did not change Zend_Form usage</li>
        <li>No plugins like Flash or Java needed, no problem with popup blockers</li>
        <li>Unobtrusive behaviour, visitors with disabled JavaScript or old browsers can still use form.</li>
    </ul>

    <h2 id="Section"><a href="#Section">Example</a></h2>

    <?php echo $this->form; ?>

</div>

<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#Title">Ajax Form</a></h4>
    <div class="menu-item"><a href="#Section">Example</a></div>
</div>
