<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">UWA Widget</a></h1>

    <h2 id="Features"><a href="#Features">Features</a></h2>

    <h2 id="Examples"><a href="#Examples">Examples</a></h2>

    <iframe height="500" src="/example/uwa"></iframe>
</div>


<div id="menu" class="span-2 last">
    <h4 class="menu-item"><a href="#Title">UWA Widget</a></h4>
    <div class="menu-item"><a href="#Features">Features</a></div>
    <div class="menu-item"><a href="#Examples">Examples</a></div>
</div>

