<div id="main" class="l-border r-border span-15">

    <h1 id="title"><a href="#Title">UWA Widget</a></h1>

    <h2 id="Features"><a href="#Features">Features</a></h2>

    <h2 id="Examples"><a href="#Examples">Environments</a></h2>

    <?php
        $uwaServerUrl = 'http://uwa.service.japanim.fr';
        $uwaWidgetUrl = MAIN_URL . '/example/uwa';
    ?>

    <h3>Stable</h3>
    <ul>
        <li><a target="_blank" href="<?php echo $this->uwaExportLink('netvibes', $uwaWidgetUrl, $uwaServerUrl); ?>">Netvibes</a></li>
        <li><a target="_blank" href="<?php echo $this->uwaExportLink('google', $uwaWidgetUrl, $uwaServerUrl); ?>">iGoogle</a></li>
        <li><a target="_blank" href="<?php echo $this->uwaExportLink('dashboard', $uwaWidgetUrl, $uwaServerUrl); ?>">Dashboard</a></li>
        <li><a target="_blank" href="<?php echo $this->uwaExportLink('screenlets', $uwaWidgetUrl, $uwaServerUrl); ?>">Screenlets</a></li>
        <li><a target="_blank" href="<?php echo $this->uwaExportLink('blogger', $uwaWidgetUrl, $uwaServerUrl); ?>">Blogger</a></li>
        <li><a target="_blank" href="<?php echo $this->uwaExportLink('live', $uwaWidgetUrl, $uwaServerUrl); ?>">Live</a></li>
        <li><a target="_blank" href="<?php echo $this->uwaExportLink('opera', $uwaWidgetUrl, $uwaServerUrl); ?>">Opera</a></li>
        <li>
            <a target="_blank" href="<?php echo $this->uwaExportLink('frame', $uwaWidgetUrl, $uwaServerUrl, array('id' => md5($this->url()))); ?>">Iframe</a>
            (
                <a target="_blank" href="<?php echo $this->uwaExportLink('frame', $uwaWidgetUrl, $uwaServerUrl, array('id' => md5($this->url()), 'header' => 1)); ?>">with header</a>
                - <a target="_blank" href="<?php echo $this->uwaExportLink('frame', $uwaWidgetUrl, $uwaServerUrl, array('id' => md5($this->url()), 'header' => 1, 'chromeColor' => 'orange')); ?>">with header color</a>
                - <a target="_blank" href="<?php echo $this->uwaExportLink('frame', $uwaWidgetUrl, $uwaServerUrl, array('id' => md5($this->url()), 'header' => 1, 'status' => 0)); ?>">without status</a>
            )
        </li>
    </ul>

    <h3>Unstable</h3>
    <ul>
        <li><a target="_blank" href="<?php echo $this->uwaExportLink('jil', $uwaWidgetUrl, $uwaServerUrl); ?>">Jil/Ophone</a> (Work in progress)</li>
        <li><a target="_blank" href="<?php echo $this->uwaExportLink('vista', $uwaWidgetUrl, $uwaServerUrl); ?>">Windows Vista/SEVEN</a> (Work in progress)</li>
    </ul>

    <h2 id="Examples"><a href="#Examples">Examples</a></h2>

    <iframe height="500" src="/example/uwa"></iframe>
</div>


<div id="menu" class="span-5 last">
    <h4 class="menu-item"><a href="#Title">UWA Widget</a></h4>
    <div class="menu-item"><a href="#Features">Features</a></div>
    <div class="menu-item"><a href="#Examples">Examples</a></div>
</div>


