<?php
/**
 * Ajax layout for MyProject
 *
 * @category   MyProject
 * @package    MyProject_App_Layouts
 * @copyright  Copyright (c) 2008 MyProject
 * @author     Harold Thetiot (hthetiot)
 */

    // Displaying javascript from controler
    $jsData = $this->javascriptData()->getData();

    if (!empty($jsData)) {
        echo '<script type="text/javascript">';
        echo $jsData;
        echo '</script>';
    }

    // display html if isAjaxHTML
    if (isset($this->isAjaxHtml)) {
        echo $this->placeholder('Zend_Layout')->content;
    }

